#!/bin/bash
set -e

case "$1" in
    purge)
        # Remove configuration files
        rm -rf /etc/tuxedo-control-center || true
        
        # Reload DBus
        if [ -d /run/systemd/system ]; then
            systemctl daemon-reload || true
            dbus-send --system --type=method_call --dest=org.freedesktop.DBus / org.freedesktop.DBus.ReloadConfig || true
        fi
        ;;
    
    remove)
        # Update icon cache
        if [ -x /usr/bin/gtk-update-icon-cache ]; then
            gtk-update-icon-cache -q -f /usr/share/icons/hicolor || true
        fi
        
        # Update desktop database
        if [ -x /usr/bin/update-desktop-database ]; then
            update-desktop-database -q /usr/share/applications || true
        fi
        ;;
esac

#DEBHELPER#

exit 0
