#!/bin/bash
set -e

case "$1" in
    remove|deconfigure)
        # Stop the daemon
        if [ -d /run/systemd/system ]; then
            systemctl stop tuxedo-daemon.service || true
            systemctl disable tuxedo-daemon.service || true
        fi
        ;;
esac

#DEBHELPER#

exit 0
